version: '3.7'

services:
   dotnettribe-ui:
    image: dotnettribeui:prod
    build:
      context: .
      dockerfile: DotNetTribe_UI/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"