
name: build and test and deploy

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
  
      - name: Install NPM dependencies
        run: npm install --prefix ./DotNetTribe_UI 
  
      - name: Restore .NET dependencies
        run: dotnet restore ./DotNetTribe_UI/./DotNetTribe_UI.csproj
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish ./DotNetTribe_UI/DotNetTribe_UI.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          permissions: write-all
          BRANCH: gh-pages
          FOLDER: dist/Web/wwwroot
